version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: omniauth_sample_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: >
      sh -c "
        bundle install &&
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails server -b 0.0.0.0"
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/omniauth_sample_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      BASE_URL: ${BASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules:
  