default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: omniauth_sample_development
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

test:
  <<: *default
  database: omniauth_sample_test
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

production:
  <<: *default
  database: omniauth_sample_production
  username: omniauth_sample_
  password: <%= ENV["OMNIAUTH_SAMPLE_DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false
  